### PR TITLE
Realistic Load Test Tool addition

### PR DESCRIPTION
**Pull request by furmangg**
@DavidMagarMS and @sergeig888 as discussed I've added our enhancements into a separate folder called RealisticLoadTestTool.

Start with the LoadTestingPowerShellTool/Readme.md and you'll see I added an explanation of both tools with a link to the RealisticLoadTestTool folder. Since the root level readme (and other places on the web) use the http://aka.ms/PowerBILoadTestingTool link I figured this would be a good way to show both options.

Please review and test and let me know if you have any questions. I hope this is a valuable addition to the community.

### CODE REVIEW

**Comment by furmangg** [comment]
You can view these changes in my fork:
https://github.com/furmangg/PowerBI-Tools-For-Capacities/tree/master/LoadTestingPowerShellTool

That will link to:
https://github.com/furmangg/PowerBI-Tools-For-Capacities/tree/master/RealisticLoadTestTool

**Comment by sergeigms** [comment]
@DavidMagarMS and @furmangg looks good.

**Comment by furmangg** [comment]
@sergeigms I missed one change that I had put on one load test but forgotten to get into the master HTML code... support for mobile views. I threw one more commit into this pull request (if I did it right). See the changes here:
https://github.com/microsoft/PowerBI-Tools-For-Capacities/pull/2/commits/c29221235b0841d3ab39e32a17fe8682e112b444

Not sure if you need to approve again

**Comment by niball** [comment]
Realistic Load Test Tool addition is not working.. Can anyone help me troubleshoot

**Pull request merged**
